'use client';

import { useState, useTransition } from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { reportText as defaultReportText } from '@/lib/data';
import { getReportSummary } from '@/app/(app)/reports/actions';
import { Loader2, Wand2 } from 'lucide-react';

export function ReportGenerator() {
  const [reportText, setReportText] = useState(defaultReportText);
  const [summary, setSummary] = useState('');
  const [isPending, startTransition] = useTransition();

  const handleGenerateSummary = () => {
    startTransition(async () => {
      const result = await getReportSummary(reportText);
      if (result.success) {
        setSummary(result.summary);
      } else {
        setSummary('Error: Could not generate summary.');
      }
    });
  };

  return (
    <div className="grid gap-6 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle className="font-headline">Financial Report Text</CardTitle>
          <CardDescription>
            This is the raw text of the financial report. You can edit it before generating a summary.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Textarea
            value={reportText}
            onChange={(e) => setReportText(e.target.value)}
            className="min-h-[400px] bg-card"
            placeholder="Paste your financial report here..."
          />
        </CardContent>
        <CardFooter>
          <Button onClick={handleGenerateSummary} disabled={isPending}>
            {isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Wand2 className="mr-2 h-4 w-4" />
            )}
            Generate AI Summary
          </Button>
        </CardFooter>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle className="font-headline">AI Generated Summary</CardTitle>
          <CardDescription>
            A concise summary of the report generated by AI.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isPending ? (
             <div className="flex items-center justify-center h-[400px]">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
             </div>
          ) : summary ? (
            <div className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap rounded-md bg-muted p-4 min-h-[400px]">
              {summary}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center text-center text-muted-foreground bg-muted rounded-md h-[400px] p-4">
                <Wand2 className="h-10 w-10 mb-4 text-primary"/>
                <p className="font-medium">Your summary will appear here.</p>
                <p className="text-sm">Click &quot;Generate AI Summary&quot; to get started.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
